# Manual-QA stack (guide/e1-verification.md is the USER doc; DECISIONS D44):
# one command from a clean machine to the seeded, running site on localhost.
#
#     .\qa-stack.ps1            # up (default): build, start, seed, print URL
#     .\qa-stack.ps1 down       # stop containers, KEEP the database volume
#     .\qa-stack.ps1 reset      # stop and WIPE the database (fresh next up)
#     .\qa-stack.ps1 status     # container list + health probes
#
# Runs the same compose file the guides document (deploy/docker-compose.yml)
# under the dedicated project name "eoe-qa", and seeds the canonical demo
# hierarchy (guide/seed-script.md, "Demo hierarchy"). POSIX users: the manual
# five-step flow in guide/getting-started.md works everywhere; this wrapper is
# Windows-first because the gate's Windows entry point is too.
#
# WARNING (D44): the gate's compose tests bind the SAME host ports
# (8000/5173/5432/6379). Run `.\qa-stack.ps1 down` before `.\gate.ps1`.

$ErrorActionPreference = "Continue"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$composeFile = Join-Path $root "deploy\docker-compose.yml"
$envFile = Join-Path $root "deploy\.env"
$project = "eoe-qa"

function Find-Uv {
    $cmd = Get-Command uv -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $winget = Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Packages"
    $hit = Get-ChildItem -Path $winget -Recurse -Filter uv.exe -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($hit) { return $hit.FullName }
    throw "uv not found; install with: winget install astral-sh.uv"
}

function Find-Docker {
    $cmd = Get-Command docker -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $fallback = "C:\Program Files\Docker\Docker\resources\bin\docker.exe"
    if (Test-Path $fallback) { return $fallback }
    throw "docker not found; install Docker Desktop"
}

function Assert-Engine {
    param([string]$Docker)
    & $Docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Docker engine is not running. Start Docker Desktop, wait for" -ForegroundColor Red
        Write-Host "the whale icon to settle, then run this script again." -ForegroundColor Red
        exit 1
    }
}

function New-RandomBase64 {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes)
}

function New-RandomHex {
    $bytes = New-Object byte[] 16
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return (($bytes | ForEach-Object { $_.ToString("x2") }) -join "")
}

function Initialize-EnvFile {
    if (Test-Path $envFile) { return }
    Write-Host "== generating deploy/.env with fresh local secrets ==" -ForegroundColor Cyan
    $pgPassword = New-RandomHex
    $lines = @(
        "# Generated by qa-stack.ps1 for LOCAL QA. Values are machine-local secrets;"
        "# this file is gitignored and must never be committed (rule R2)."
        "POSTGRES_USER=eoe"
        "POSTGRES_PASSWORD=$pgPassword"
        "POSTGRES_DB=eoe"
        "DATABASE_URL=postgresql+psycopg://eoe:$pgPassword@postgres:5432/eoe"
        "EOE_SESSION_SECRET=$(New-RandomBase64)"
        "EOE_KEK=$(New-RandomBase64)"
        "REDIS_URL=redis://redis:6379/0"
        "EOE_CORS_ORIGINS=http://localhost:5173"
        "EOE_FRONTEND_API_URL=http://localhost:8000"
    )
    # ASCII content only, so encoding is a non-issue for compose and python.
    Set-Content -Path $envFile -Value $lines -Encoding ascii
    Write-Host "   deploy/.env written (values not shown; delete the file to rotate)"
}

function Read-EnvFile {
    $values = @{}
    foreach ($line in Get-Content $envFile) {
        if ($line -match "^\s*#" -or $line -notmatch "=") { continue }
        $name, $value = $line -split "=", 2
        $values[$name.Trim()] = $value.Trim()
    }
    return $values
}

function Invoke-Compose {
    param([string[]]$ComposeArgs)
    $docker = Find-Docker
    & $docker compose -f $composeFile -p $project --env-file $envFile @ComposeArgs
}

function Test-Health {
    $ok = $true
    try {
        $health = Invoke-RestMethod -Uri "http://localhost:8000/api/v1/health" -TimeoutSec 5
        if ($health.status -eq "ok" -and $health.database -eq "ok") {
            Write-Host "   API healthy at http://localhost:8000 (build $($health.build_sha))"
        } else {
            Write-Host "   API responded but is not healthy: $($health | ConvertTo-Json -Compress)" -ForegroundColor Red
            $ok = $false
        }
    } catch {
        Write-Host "   API unreachable at http://localhost:8000" -ForegroundColor Red
        $ok = $false
    }
    try {
        $front = Invoke-WebRequest -Uri "http://localhost:5173/" -TimeoutSec 5 -UseBasicParsing
        if ($front.StatusCode -eq 200) {
            Write-Host "   frontend serving at http://localhost:5173"
        } else {
            Write-Host "   frontend answered $($front.StatusCode)" -ForegroundColor Red
            $ok = $false
        }
    } catch {
        Write-Host "   frontend unreachable at http://localhost:5173" -ForegroundColor Red
        $ok = $false
    }
    return $ok
}

function Show-GateWarning {
    Write-Host ""
    Write-Host "  +---------------------------------------------------------------+" -ForegroundColor Yellow
    Write-Host "  | Before running .\gate.ps1: run  .\qa-stack.ps1 down           |" -ForegroundColor Yellow
    Write-Host "  | The gate's compose tests bind the same ports                  |" -ForegroundColor Yellow
    Write-Host "  | (8000 / 5173 / 5432 / 6379) and will go RED otherwise (D44).  |" -ForegroundColor Yellow
    Write-Host "  +---------------------------------------------------------------+" -ForegroundColor Yellow
}

$verb = if ($args.Count -gt 0) { $args[0] } else { "up" }

switch ($verb) {
    "up" {
        $docker = Find-Docker
        Assert-Engine $docker
        Initialize-EnvFile
        Write-Host ""
        Write-Host "== starting the stack (project $project) ==" -ForegroundColor Cyan
        Invoke-Compose @("up", "-d", "--build", "--wait")
        if ($LASTEXITCODE -ne 0) {
            Write-Host "compose failed to start; inspect with:" -ForegroundColor Red
            Write-Host "  docker compose -f deploy/docker-compose.yml -p $project logs" -ForegroundColor Red
            exit 1
        }
        Write-Host ""
        Write-Host "== seeding the demo hierarchy ==" -ForegroundColor Cyan
        $values = Read-EnvFile
        $env:DATABASE_URL = $values["DATABASE_URL"] -replace "@postgres:", "@localhost:"
        $env:EOE_SESSION_SECRET = $values["EOE_SESSION_SECRET"]
        $env:EOE_KEK = $values["EOE_KEK"]
        $uv = Find-Uv
        Push-Location (Join-Path $root "backend")
        try {
            & $uv run python -m app.seed --demo
            $seedExit = $LASTEXITCODE
        }
        finally { Pop-Location }
        if ($seedExit -ne 0) {
            # The seed refuses reruns by design (D43): an existing demo
            # hierarchy is the expected idempotent path, not a failure.
            Write-Host "   already seeded - credentials were printed on the first 'up'." -ForegroundColor Yellow
            Write-Host "   Forgot them? Run:  .\qa-stack.ps1 reset   then 'up' again." -ForegroundColor Yellow
        }
        Write-Host ""
        Write-Host "== health ==" -ForegroundColor Cyan
        $healthy = Test-Health
        Write-Host ""
        if ($healthy) {
            Write-Host "QA STACK READY" -ForegroundColor Green
            Write-Host "  site:        http://localhost:5173"
            Write-Host "  walkthrough: guide/e1-verification.md"
            Write-Host "  teardown:    .\qa-stack.ps1 down   (keeps data)  |  reset (wipes data)"
        } else {
            Write-Host "QA STACK UNHEALTHY - see messages above" -ForegroundColor Red
        }
        Show-GateWarning
        if (-not $healthy) { exit 1 }
        exit 0
    }
    "down" {
        Assert-Engine (Find-Docker)
        Initialize-EnvFile  # compose interpolates the env file on every command
        Invoke-Compose @("down", "--remove-orphans")
        Write-Host "stack stopped; the database volume is kept (reset wipes it)" -ForegroundColor Green
        exit $LASTEXITCODE
    }
    "reset" {
        Assert-Engine (Find-Docker)
        Initialize-EnvFile
        Invoke-Compose @("down", "-v", "--remove-orphans")
        Write-Host "stack stopped and database wiped; next 'up' seeds fresh credentials" -ForegroundColor Green
        exit $LASTEXITCODE
    }
    "status" {
        Assert-Engine (Find-Docker)
        Initialize-EnvFile
        Invoke-Compose @("ps")
        Write-Host ""
        $null = Test-Health
        exit 0
    }
    default {
        Write-Host "usage: .\qa-stack.ps1 [up|down|reset|status]"
        exit 2
    }
}
