"""quarantine_and_alerts

Revision ID: 05c4858bfab5
Revises: 53181716569c
Create Date: 2026-08-02 19:41:46.308773

Reversibility is mandatory: downgrade() must fully undo upgrade()
(docs/migration-conventions.md). Autogenerate output is a draft; review it
by hand before committing.
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

revision: str = "05c4858bfab5"
down_revision: str | None = "53181716569c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_alert",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_type", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_key", sa.String(length=100), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_alert")),
    )
    op.create_index(
        op.f("ix_inventory_alert_deployment_id"), "inventory_alert", ["deployment_id"], unique=False
    )
    op.create_index(
        "uq_inventory_alert_open",
        "inventory_alert",
        ["alert_type", "entity_type", "entity_key"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_table(
        "quarantined_report",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mac", sa.String(length=17), nullable=False),
        sa.Column("reported_name", sa.String(length=200), nullable=True),
        sa.Column("aggregator_uuid", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantined_report")),
    )
    op.create_index(
        op.f("ix_quarantined_report_aggregator_uuid"),
        "quarantined_report",
        ["aggregator_uuid"],
        unique=False,
    )
    op.create_index(op.f("ix_quarantined_report_mac"), "quarantined_report", ["mac"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quarantined_report_mac"), table_name="quarantined_report")
    op.drop_index(op.f("ix_quarantined_report_aggregator_uuid"), table_name="quarantined_report")
    op.drop_table("quarantined_report")
    op.drop_index(
        "uq_inventory_alert_open",
        table_name="inventory_alert",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_index(op.f("ix_inventory_alert_deployment_id"), table_name="inventory_alert")
    op.drop_table("inventory_alert")
    # ### end Alembic commands ###
