"""hierarchy_tables

Revision ID: ee260dc1c1a8
Revises: 0dd2c6d5b1d2
Create Date: 2026-08-02 18:58:00.932342

Reversibility is mandatory: downgrade() must fully undo upgrade()
(docs/migration-conventions.md). Autogenerate output is a draft; review it
by hand before committing.
"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

revision: str = "ee260dc1c1a8"
down_revision: str | None = "0dd2c6d5b1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
        sa.UniqueConstraint("name", name=op.f("uq_organization_name")),
    )
    op.create_index(
        "ix_organization_tags", "organization", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "deployment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'", name=op.f("ck_deployment_slug_format")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_deployment_organization_id_organization"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment")),
        sa.UniqueConstraint("organization_id", "name", name=op.f("uq_deployment_organization_id")),
    )
    op.create_index(
        op.f("ix_deployment_organization_id"), "deployment", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_deployment_slug"), "deployment", ["slug"], unique=True)
    op.create_index(
        "ix_deployment_tags", "deployment", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "pod",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployment.id"], name=op.f("fk_pod_deployment_id_deployment")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pod")),
        sa.UniqueConstraint("deployment_id", "name", name=op.f("uq_pod_deployment_id")),
    )
    op.create_index(op.f("ix_pod_deployment_id"), "pod", ["deployment_id"], unique=False)
    op.create_index("ix_pod_tags", "pod", ["tags"], unique=False, postgresql_using="gin")
    op.create_table(
        "aggregator",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pod_id", sa.Uuid(), nullable=False),
        sa.Column("aggregator_uuid", sa.String(length=64), nullable=False),
        sa.Column("balena_uuid", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pod_id"], ["pod.id"], name=op.f("fk_aggregator_pod_id_pod")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aggregator")),
        sa.UniqueConstraint("pod_id", name=op.f("uq_aggregator_pod_id")),
    )
    op.create_index(
        op.f("ix_aggregator_aggregator_uuid"), "aggregator", ["aggregator_uuid"], unique=True
    )
    op.create_index(
        "ix_aggregator_tags", "aggregator", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "listener",
        sa.Column("mac", sa.String(length=17), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("aggregator_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("gps_lat", sa.Float(), nullable=True),
        sa.Column("gps_lon", sa.Float(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mac ~ '^[0-9A-F]{2}(:[0-9A-F]{2}){5}$'", name=op.f("ck_listener_mac_format")
        ),
        sa.ForeignKeyConstraint(
            ["aggregator_id"], ["aggregator.id"], name=op.f("fk_listener_aggregator_id_aggregator")
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployment.id"], name=op.f("fk_listener_deployment_id_deployment")
        ),
        sa.PrimaryKeyConstraint("mac", name=op.f("pk_listener")),
        sa.UniqueConstraint("deployment_id", "name", name=op.f("uq_listener_deployment_id")),
    )
    op.create_index(op.f("ix_listener_aggregator_id"), "listener", ["aggregator_id"], unique=False)
    op.create_index(op.f("ix_listener_deployment_id"), "listener", ["deployment_id"], unique=False)
    op.create_index("ix_listener_tags", "listener", ["tags"], unique=False, postgresql_using="gin")
    # Hand-adjusted: the role_assignment.deployment_id foreign key moves to the
    # next revision, which pairs it with the orphan-grant data step (D33).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_listener_tags", table_name="listener", postgresql_using="gin")
    op.drop_index(op.f("ix_listener_deployment_id"), table_name="listener")
    op.drop_index(op.f("ix_listener_aggregator_id"), table_name="listener")
    op.drop_table("listener")
    op.drop_index("ix_aggregator_tags", table_name="aggregator", postgresql_using="gin")
    op.drop_index(op.f("ix_aggregator_aggregator_uuid"), table_name="aggregator")
    op.drop_table("aggregator")
    op.drop_index("ix_pod_tags", table_name="pod", postgresql_using="gin")
    op.drop_index(op.f("ix_pod_deployment_id"), table_name="pod")
    op.drop_table("pod")
    op.drop_index("ix_deployment_tags", table_name="deployment", postgresql_using="gin")
    op.drop_index(op.f("ix_deployment_slug"), table_name="deployment")
    op.drop_index(op.f("ix_deployment_organization_id"), table_name="deployment")
    op.drop_table("deployment")
    op.drop_index("ix_organization_tags", table_name="organization", postgresql_using="gin")
    op.drop_table("organization")
    # ### end Alembic commands ###
