"""Dev broker provisioning (task E3.1; spec 7.1).

    uv run python -m app.devbroker --certs-only    # CA + server cert, no DB
    uv run python -m app.devbroker                 # + accounts, ACLs, service rows

Spec 7.1 puts a TLS Mosquitto beside every deployment, with the platform
holding broker-wide access inside that deployment's namespace and each
Aggregator restricted by per-topic ACL to its own subtree. Development gets
the same shape from day one — one container, real TLS, real per-device
credentials, real ACLs — because a control plane first exercised without TLS
grows code that quietly assumes plaintext.

Everything this writes is a THROWAWAY DEV ARTIFACT under `deploy/dev-certs/`,
which is gitignored: a private CA, a server certificate, generated passwords,
a Mosquitto password file and an ACL file. Nothing here belongs in a real
deployment, and re-running rotates every credential (the password file and
the SecretStore entries are rewritten in the same pass, so they cannot drift
apart). E4/E5 own real per-device credential minting; this is dev scaffolding.

Two passes exist because of a bootstrap order: Mosquitto will not start
without its password and ACL files, but the accounts in them come from the
database that starts beside it. `--certs-only` writes the certificates and
empty account files so the stack can come up; the full run then fills in the
accounts and reloads the broker.
"""

import argparse
import json
import secrets
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.brokerconfig import (
    CERT_HOSTNAMES,
    CERT_IPS,
    PW_HASH_BYTES,
    PW_ITERATIONS,
    PW_SALT_BYTES,
    Account,
    AclGrant,
    aggregator_acl_grants,
    device_username,
    generate_tls_material,
    password_file_text,
    password_hash,
    platform_username,
)
from app.contracts.mqtt import deployment_root
from app.db import create_session_factory
from app.models import Aggregator, Deployment, DeploymentService, Pod
from app.secrets import SecretStore
from app.settings import Settings

#: Re-exported so E3.1's callers and `tests/test_dev_broker.py` keep importing
#: the broker material from here. E5.8a moved the implementations to
#: `app.brokerconfig` because the generated stack needs the same renderers; the
#: names this module has always exposed are deliberately unchanged.
__all__ = [
    "CERT_HOSTNAMES",
    "CERT_IPS",
    "DEV_CERTS",
    "PW_HASH_BYTES",
    "PW_ITERATIONS",
    "PW_SALT_BYTES",
    "AclGrant",
    "Account",
    "acl_file_text",
    "aggregator_acl_grants",
    "device_username",
    "generate_tls_material",
    "load_manifest",
    "main",
    "password_file_text",
    "password_hash",
    "plan_accounts",
    "platform_username",
    "register_services",
    "secret_name",
    "write_artifacts",
]

REPO_ROOT = Path(__file__).resolve().parents[2]
DEV_CERTS = REPO_ROOT / "deploy" / "dev-certs"

DEFAULT_HOST = "localhost"
DEFAULT_PORT = 8883


def secret_name(deployment_id: object, service_key: str = "mqtt") -> str:
    """The SecretStore name for a service password (INTERFACES, SecretStore
    section: the `deployment:{id}:*` namespace)."""
    return f"deployment:{deployment_id}:{service_key}_password"


# --- Mosquitto ACL file -----------------------------------------------------
#
# The password file and the TLS material are rendered by `app.brokerconfig`
# (E5.8a); this file is the dev broker's own authorisation mechanism and stays
# here, because a generated stack authorises with the dynamic security plugin
# instead and never writes one.


def acl_file_text(accounts: list[Account]) -> str:
    """The ACL file. With `acl_file` set, Mosquitto denies every topic it was
    not explicitly granted, so this file IS the isolation guarantee of spec
    7.1 — the device grants come from `aggregator_acl_grants`, which is the
    spec 7.2 table's Direction column read literally, and which the dynsec
    role of every minted credential is rendered from as well (E5.6).
    """
    blocks: list[str] = [
        "# GENERATED by app.devbroker (task E3.1) - do not edit by hand.",
        "# Mosquitto denies any topic not granted here.",
        "",
    ]
    for account in accounts:
        if account.kind == "platform":
            blocks += [
                "# platform account: broker-wide inside one deployment (spec 7.1)",
                f"user {account.username}",
                f"topic readwrite {deployment_root(account.deployment_slug)}/#",
                "",
            ]
            continue
        assert account.aggregator_uuid is not None
        blocks += [
            "# aggregator: its own subtree only, one grant per spec 7.2 row",
            f"user {account.username}",
            *[
                f"topic {grant.access} {grant.topic}"
                for grant in aggregator_acl_grants(account.deployment_slug, account.aggregator_uuid)
            ],
            "",
        ]
    return "\n".join(blocks)


# --- Writing the artifact directory ----------------------------------------


def write_artifacts(
    out_dir: Path,
    accounts: list[Account],
    *,
    host: str,
    port: int,
    regenerate_tls: bool,
) -> None:
    """Write (or refresh) the whole dev-certs directory.

    The directory and the private keys land world-readable on purpose: the
    Mosquitto container drops to uid 1883 and can neither traverse a 0700
    directory nor read a 0600 file that arrived from the host. These keys
    protect nothing — they are generated, gitignored, and rotated on every run
    — and the alternative is an init container whose only job is a chown."""
    out_dir.mkdir(parents=True, exist_ok=True)
    try:
        out_dir.chmod(0o755)
    except PermissionError as error:
        # Docker creates a missing bind-mount source directory as root. If the
        # stack came up before this ever ran, `deploy/dev-certs` exists but
        # belongs to root and nothing here can write into it. Say so plainly:
        # the raw errno is a genuinely baffling way to learn this.
        raise SystemExit(
            f"cannot write to {out_dir}: it exists but is not owned by you.\n"
            "Docker created it as root when the stack came up before the "
            "certificates existed. Remove it and run this again:\n"
            f'  docker run --rm -v "{out_dir.parent}:/work" alpine:3 '
            f"rm -rf /work/{out_dir.name}"
        ) from error
    if regenerate_tls or not (out_dir / "ca.crt").is_file():
        for name, blob in generate_tls_material().items():
            path = out_dir / name
            path.write_bytes(blob)
            path.chmod(0o644)

    (out_dir / "passwd").write_text(password_file_text(accounts), encoding="utf-8")
    (out_dir / "acl").write_text(acl_file_text(accounts), encoding="utf-8")
    (out_dir / "passwd").chmod(0o644)
    (out_dir / "acl").chmod(0o644)

    manifest = {
        "host": host,
        "port": port,
        "ca_cert": str((out_dir / "ca.crt").resolve()),
        "accounts": [asdict(account) for account in accounts],
    }
    (out_dir / "accounts.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_manifest(out_dir: Path = DEV_CERTS) -> dict[str, Any]:
    """Read back what the last run wrote — how the test suite and the mock
    device learn their credentials without a second source of truth."""
    manifest: dict[str, Any] = json.loads((out_dir / "accounts.json").read_text(encoding="utf-8"))
    return manifest


# --- Database side ----------------------------------------------------------


def plan_accounts(db: Session) -> list[Account]:
    """One platform account per deployment plus one device account per
    Aggregator, with freshly generated passwords."""
    accounts: list[Account] = []
    for slug in db.scalars(select(Deployment.slug).order_by(Deployment.slug)):
        accounts.append(
            Account(
                username=platform_username(slug),
                password=secrets.token_urlsafe(24),
                kind="platform",
                deployment_slug=slug,
            )
        )
    rows = db.execute(
        select(Deployment.slug, Aggregator.aggregator_uuid)
        .join(Pod, Pod.deployment_id == Deployment.id)
        .join(Aggregator, Aggregator.pod_id == Pod.id)
        .order_by(Deployment.slug, Aggregator.aggregator_uuid)
    )
    for slug, aggregator_uuid in rows:
        accounts.append(
            Account(
                username=device_username(aggregator_uuid),
                password=secrets.token_urlsafe(24),
                kind="device",
                deployment_slug=slug,
                aggregator_uuid=aggregator_uuid,
            )
        )
    return accounts


def register_services(
    db: Session,
    secret_store: SecretStore,
    accounts: list[Account],
    *,
    host: str,
    port: int,
    ca_cert_pem: str,
) -> int:
    """Upsert the `mqtt` deployment_service row for every deployment that got
    a platform account, putting the password through SecretStore and never
    into the row (rule R2). Returns the number of rows written."""
    by_slug = {a.deployment_slug: a for a in accounts if a.kind == "platform"}
    written = 0
    for deployment in db.scalars(select(Deployment).order_by(Deployment.slug)):
        account = by_slug.get(deployment.slug)
        if account is None:
            continue
        row = db.scalar(
            select(DeploymentService).where(
                DeploymentService.deployment_id == deployment.id,
                DeploymentService.service_key == "mqtt",
            )
        )
        if row is None:
            row = DeploymentService(deployment_id=deployment.id, service_key="mqtt")
            db.add(row)
        row.host = host
        row.port = port
        row.tls_enabled = True
        row.ca_cert_pem = ca_cert_pem
        row.username = account.username
        row.password_secret_name = secret_name(deployment.id)
        secret_store.put(row.password_secret_name, account.password)
        written += 1
    db.commit()
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Provision the development MQTT broker (E3.1)")
    parser.add_argument("--host", default=DEFAULT_HOST, help="broker host the PLATFORM dials")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--out", type=Path, default=DEV_CERTS)
    parser.add_argument(
        "--certs-only",
        action="store_true",
        help="TLS material and empty account files only; touches no database",
    )
    parser.add_argument(
        "--keep-tls",
        action="store_true",
        help="reuse existing certificates instead of regenerating them",
    )
    args = parser.parse_args(argv)

    if args.certs_only:
        write_artifacts(args.out, [], host=args.host, port=args.port, regenerate_tls=True)
        print(f"dev broker TLS material written to {args.out} (no accounts yet)")
        return 0

    settings = Settings()  # type: ignore[call-arg]
    _, session_factory = create_session_factory(settings.database_url)
    secret_store = SecretStore(session_factory, settings.kek)
    with session_factory() as db:
        accounts = plan_accounts(db)
        if not accounts:
            print("no deployments found; seed one first (uv run python -m app.seed --demo)")
            return 1
        write_artifacts(
            args.out,
            accounts,
            host=args.host,
            port=args.port,
            regenerate_tls=not args.keep_tls,
        )
        ca_cert_pem = (args.out / "ca.crt").read_text(encoding="utf-8")
        written = register_services(
            db,
            secret_store,
            accounts,
            host=args.host,
            port=args.port,
            ca_cert_pem=ca_cert_pem,
        )

    platform = sum(1 for a in accounts if a.kind == "platform")
    devices = len(accounts) - platform
    print(
        f"dev broker provisioned in {args.out}: {platform} platform account(s), "
        f"{devices} device account(s), {written} deployment_service row(s)"
    )
    print("restart the broker so it reloads passwd/acl:  docker compose restart mosquitto")
    return 0


if __name__ == "__main__":
    sys.exit(main())
